name: Autograding Tests

'on':
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # بررسی وجود requirements.txt

      - name: Run Python tests
        id: python-test
        run: |
          pytest tests/ --tb=short --disable-warnings | tee pytest-results.txt
          echo "PYTHON_TEST_RESULTS=$(cat pytest-results.txt)" >> $GITHUB_ENV  # ذخیره نتیجه تست‌ها

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: python-test
          timeout: 10
          max-score: 20
        env:
          PYTHON-TEST_RESULTS: "${{ env.PYTHON_TEST_RESULTS }}"